---
# Tasks file for apply_individual_ptf
- name: Apply individual PTF with ibm.power_ibmi.ibmi_fix
  ibm.power_ibmi.ibmi_fix:
    product_id: "{{ apply_ptf.product }}"
    fix_list: "{{ apply_ptf.ptf_id }}"
    operation: 'apply_only'
    delayed_option: '{{ apply_ptf_delayed_option }}'
    temp_or_perm: '{{ apply_ptf_temp_or_perm }}'
  ignore_errors: true
  register: apply_ptf_result

# - ansible.builtin.debug:
#     var: apply_fix_result

- name: Log failure in result
  ansible.builtin.set_fact:
    apply_ptf_apply_fail_list: "{{ apply_ptf_apply_fail_list | default([]) + [apply_ptf] }}"
  when: apply_ptf_result.failed != 0

- name: Check if IPL is required for PTF
  when: apply_ptf_result.failed == 0
  block:
    - name: Log success in result
      ansible.builtin.set_fact:
        apply_ptf_apply_success_list: "{{ apply_ptf_apply_success_list | default([]) + [apply_ptf] }}"

    - name: Query PTF with only required options
      ibm.power_ibmi.ibmi_fix:
        fix_list: '{{ apply_ptf.ptf_id }}'
        operation: 'query'
      register: fix_result
      when: apply_ptf_auto_ipl

    - name: Reboot the system immediately if apply_ptf_auto_ipl is set to true and at least one to-be-applied PTF requires an IPL
      ansible.builtin.set_fact:
        ipl_requested: true
      when:
        - apply_ptf_auto_ipl
        - fix_result['ptf_list'][0]['PTF_IPL_ACTION'] == 'TEMPORARILY APPLIED' or fix_result['ptf_list'][0]['PTF_IPL_ACTION'] == 'PERMANENTLY APPLIED'
