# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
# Default values for display_vm_info_via_powervc
display_vm_info_via_powervc_project: ibm-default
display_vm_info_via_powervc_project_domain: Default
display_vm_info_via_powervc_user_domain: Default
display_vm_info_via_powervc_verify_cert: true
