---
# Role for fix_repo_download_add_ptf_group
# Call ibm.power_ibmi.ibmi_download_fix module to download ptf group,
# then call ibm.power_ibmi.ibmi_fix_repo module to add information into download_status table in catalog.
- name: Download PTF group
  ibm.power_ibmi.ibmi_download_fix:
    ptf_id: "{{ fix_repo_download_add_ptf_group_ptf_group_info.ptf_group_number }}"
    delivery_format: "*IMAGE"
    reorder: "*YES"
  register: fix_repo_download_add_ptf_group_download_fix_result

- name: Print download information
  ansible.builtin.debug:
    var: fix_repo_download_add_ptf_group_download_fix_result

- name: Add order information into download_status table
  ibm.power_ibmi.ibmi_fix_repo:
    type: "download_status"
    action: "add"
    parameters:
      - "{{ {'order_id': fix_repo_download_add_ptf_group_download_fix_result.order_id,
             'file_path': fix_repo_download_add_ptf_group_download_fix_result.file_path,
             'ptf_group_number': fix_repo_download_add_ptf_group_ptf_group_info.ptf_group_number,
             'ptf_group_level': fix_repo_download_add_ptf_group_ptf_group_info.ptf_group_level,
             'release_date': fix_repo_download_add_ptf_group_ptf_group_info.release_date, 'download_status': 'DOWNLOADING'} }}"
  register: fix_repo_download_add_ptf_group_download_status_add_result
  when: fix_repo_download_add_ptf_group_download_fix_result.order_id is defined

- name: Add part of PTF group information including ptf list into catalog, in order that ptf_list can contain product info
  ibm.power_ibmi.ibmi_fix_repo:
    type: "ptf_group"
    action: "add"
    checksum: false
    parameters:
      - "{{ {'order_id': fix_repo_download_add_ptf_group_download_fix_result.order_id,
             'file_path': fix_repo_download_add_ptf_group_download_fix_result.file_path,
             'ptf_group_number': fix_repo_download_add_ptf_group_ptf_group_info.ptf_group_number,
             'ptf_list': fix_repo_download_add_ptf_group_ptf_group_info.ptf_list,
             'ptf_group_level': fix_repo_download_add_ptf_group_ptf_group_info.ptf_group_level,
             'release_date': fix_repo_download_add_ptf_group_ptf_group_info.release_date,
             'description': fix_repo_download_add_ptf_group_ptf_group_info.description,
             'release': fix_repo_download_add_ptf_group_ptf_group_info.release} }}"
  register: ptf_group_update_result
  when: fix_repo_download_add_ptf_group_download_fix_result.order_id is defined

- name: Print add order information result
  ansible.builtin.debug:
    var: fix_repo_download_add_ptf_group_download_status_add_result
