---
# New vm info from OpenStack
- name: Deploy a new VM
  openstack.cloud.server:
    auth:
      auth_url: https://{{ ansible_ssh_host }}:5000/v3
      username: '{{ ansible_ssh_user }}'
      password: '{{ ansible_ssh_pass }}'
      project_name: '{{ deploy_vm_via_powervc_project }}'
      project_domain_name: '{{ deploy_vm_via_powervc_project_domain }}'
      user_domain_name: '{{ deploy_vm_via_powervc_user_domain }}'
    name: '{{ deploy_vm_via_powervc_vm_name }}'
    image: '{{ deploy_vm_via_powervc_image_name_or_id }}'
    flavor: '{{ deploy_vm_via_powervc_flavor_name_or_id }}'
    validate_certs: '{{ deploy_vm_via_powervc_validate_certs }}'
    nics: '{{ deploy_vm_via_powervc_nic_list }}'
    timeout: '{{ deploy_vm_via_powervc_deploy_timeout }}'
    userdata: '{{ deploy_vm_via_powervc_deploy_userdata }}'
    availability_zone: '{{ deploy_vm_via_powervc_availability_zone_name }}'
    key_name: '{{ deploy_vm_via_powervc_key_name_shown_on_powervc }}'
  register: deploy_vm_via_powervc_server_info
