---
- name: Check if a set of individual PTFs are already in fix management catalog, then download non-existent PTFs
  # Description:
  # This playbook will check if requested individual PTFs are already in catalog, if not, will call download_individual_ptfs role
  # to download non-existent ptfs and write individual PTFs' information into catalog.

  # Parameters:
  # repo_server -- The IBM i server which can use SNDPTFORD to download and store PTF install files.

  # Command example: ansible-playbook ./check_download_individual_ptfs.yml
  #                      -e "{'repo_server': 'reposerver', 'ptfs_list': ['SI67856', 'SI69375', 'SI73751']}"

  hosts: "{{ repo_server | default([]) }}"
  gather_facts: false

  vars:
    fix_repo_check_download_individual_ptfs_ptfs_list_parm: "{{ ptfs_list }}"
    fix_repo_check_download_individual_ptfs_repo_server: "{{ repo_server }}"

  tasks:
    - name: Include fix_repo_check_download_individual_ptfs role to check and download a list of individual ptfs
      ansible.builtin.include_role:
        name: fix_repo_check_download_individual_ptfs
