# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# Description:
  # This playbook will copy individual ptf files on Ansible server to repo server, and create dir on repo server named after the ptf

# Parameters:
  # repo_server   -- The IBM i/Linux server stores PTFs and PTF groups.
  # ptf_number    -- Specifies the PTF number which needs to be copied to repo server.
  # file_path_dir -- The directory of PTF files on repo server.

# Command example:
  # ansible-playbook /copy_individual_ptf_to_repo.yml -e "{'repo_server': 'systemB', 'ptf_number': 'SI63556', 'file_path_dir': '/tmp/SI63556'}"
---
- name: Copy individual ptf files from Ansible server to repo server
  hosts: '{{ repo_server | default([]) }}'
  gather_facts: false

  vars:
    ptf_number: "{{ ptf_number }}"
    file_path_dir: "{{ file_path_dir }}"

  tasks:
    - name: Compose repo dir
      ansible.builtin.set_fact:
        repo_dir: "~/PTF/{{ ptf_number }}"

    - name: Debug repo_dir
      ansible.builtin.debug:
        var: repo_dir

    - name: Clear receive dir
      ansible.builtin.file:
        path: "{{ repo_dir }}"
        state: absent
      register: clear_result
      ignore_errors: true

    - name: Debug clear_result
      ansible.builtin.debug:
        var: clear_result

    - name: Make receive dir
      ansible.builtin.file:
        path: "{{ repo_dir }}"
        state: directory
        mode: "0755"
      register: file_result
      ignore_errors: true

    - name: Debug file_result
      ansible.builtin.debug:
        var: file_result

    - name: Block to check on receive dir creation failure
      when: file_result.failed == 1
      block:
        - name: Skip when make receive dir fail
          ansible.builtin.debug:
            msg: "{{ 'Make receive dir ' + repo_dir + ' fail, end host.' }}"

        - name: End host
          ansible.builtin.meta: end_host

    - name: Copy files to repo
      ansible.builtin.copy:
        src: "{{ file_path_dir }}//"
        dest: "{{ repo_dir }}"
        force: true
        mode: preserve
      register: copy_result

    - name: Print out successful msg
      ansible.builtin.debug:
        msg: "Files under {{ file_path_dir }} are successfully copied to {{ repo_dir }}"
