# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# Description:
  # The sample file is to provide an example about how to compare the ptf groups between repo server and IBM i.

# Parameters:
  # repo_server   -- The IBM i server which can use SNDPTFORD to download and store PTF and PTF group install files.
  # target_system -- The target IBM i server which needs to be compared with repo server.
  # group_list    -- The PTF group list

# Command example:
  # ansible-playbook ./ibmi_fix_group_compare.yml -e "{'group_list':['SF99xxx','SF99yyy'], 'target_system': 'target', 'repo_server': 'reposerver'}"
---
- name: Playbook to compare ptf groups between the repo server and target IBM i
  hosts: '{{ target_system | default([]) }}'
  gather_facts: false

  vars:
    group_list: []
    check_ptf_groups_against_fix_repo_repo_server: "{{repo_server}}"
    check_ptf_groups_against_fix_repo_type: "latest"

  tasks:
    - name: Compare the groups
      ansible.builtin.include_role:
        name: check_ptf_groups_against_fix_repo
      vars:
        check_ptf_groups_against_fix_repo_group_list: "{{ group_list }}"

    - name: Print group status
      ansible.builtin.debug:
        var: check_ptf_groups_against_fix_repo_group_status
