---
# Tasks file for download_individual_ptfs
- name: Initialize download_success_list and download_fail_list
  ansible.builtin.set_fact:
    download_individual_ptfs_download_success_list: []
    download_individual_ptfs_download_fail_list: []

- name: Download ptfs from save file
  ansible.builtin.include_tasks: download_individual_ptf.yml
  loop: "{{ download_individual_ptfs_to_be_downloaded_list }}"
  loop_control:
    loop_var: download_ptf

- name: Print the successful download list
  ansible.builtin.debug:
    var: download_individual_ptfs_download_success_list

- name: Print the failed download list
  ansible.builtin.debug:
    var: download_individual_ptfs_download_fail_list
