# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
# Tasks file for apply_all_loaded_ptfs
- name: Apply all loaded ptfs with ibmi_fix
  ibm.power_ibmi.ibmi_fix:
    product_id: "*ALL"
    delayed_option: '{{ apply_all_loaded_ptfs_delayed_option }}'
    temp_or_perm: '{{ apply_all_loaded_ptfs_temp_or_perm }}'
    operation: 'apply_only'
  register: apply_fix_result

- name: Query the list of to-be-applied ptfs which require an IPL
  ibm.power_ibmi.ibmi_sql_query:
    sql: "SELECT PTF_IDENTIFIER, PTF_IPL_ACTION, A.*
  FROM QSYS2.PTF_INFO A
  WHERE PTF_IPL_ACTION = 'TEMPORARILY APPLIED' \
  or PTF_IPL_ACTION = 'PERMANENTLY APPLIED'"
  register: query_ptf_result

- name: |
    Reboot the system immediately if apply_all_loaded_ptfs_auto_ipl is set to true and at
    least one to-be-applied PTF requires an IPL
  ibm.power_ibmi.ibmi_reboot:
  when: apply_all_loaded_ptfs_auto_ipl and query_ptf_result.row | length > 0
