# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
---
# Default values for deploy_vm_via_powervc
deploy_vm_via_powervc_project: ibm-default
deploy_vm_via_powervc_project_domain: Default
deploy_vm_via_powervc_user_domain: Default
deploy_vm_via_powervc_validate_certs: true
deploy_vm_via_powervc_flavor_name_or_id: tiny
deploy_vm_via_powervc_deploy_timeout: 300
deploy_vm_via_powervc_availability_zone_name: 'Default Group'
deploy_vm_via_powervc_key_name_shown_on_powervc: ''
deploy_vm_via_powervc_deploy_userdata: |
  {%- raw -%}#!/bin/sh
  system "chgtcpsvr svrspcval(*sshd) autostart(*yes)"
  system "strtcpsvr *sshd"
  {% endraw %}
