# Copyright (c) IBM Corporation 2019, 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

## This role configures an IP interface
---

- name: Fail the task if internet_address is not provided.
  ansible.builtin.fail:
    msg: 'Required parameter present_ip_interface_ip_address is not provided or its value is "", please check it'
  when: not present_ip_interface_ip_address

- name: Set a returned variable to indicate if the interface be configured successfully
  ansible.builtin.set_fact:
    configured_result: pass
    interface_exists: false
    lind_exists: false
    lind_active: false
    resource_name: ''

- name: Query ip interfaces from source system
  ibm.power_ibmi.ibmi_sql_query:
    sql: "SELECT INTERNET_ADDRESS,CONNECTION_TYPE,SUBNET_MASK,PREFIX_LENGTH,LINE_DESCRIPTION,
    VIRTUAL_LAN_ID,PREFIX_LENGTH from QSYS2.NETSTAT_INTERFACE_INFO WHERE (INTERNET_ADDRESS =
    '{{ present_ip_interface_ip_address }}') AND (INTERFACE_LINE_TYPE = 'ELAN' OR INTERFACE_LINE_TYPE = 'VETH'
    OR LINE_DESCRIPTION = '*VIRTUALIP') AND INTERNET_ADDRESS not in ('*IP6SAC', '*IP4DHCP')"
  register: existing_ip_interfaces

- name: Create a new IP interface when it doesn't exist
  when: existing_ip_interfaces.row|length == 0
  block:
    - name: Print msg
      ansible.builtin.debug:
        msg: Start creating IP interface

    - name: Find the resource name of ethernet port when line description name is not provided
      ansible.builtin.include_tasks: find_resource_name_of_ethernet_port.yml
      when: present_ip_interface_line_description is undefined or present_ip_interface_line_description == None

    - name: Run WRKCFGSTS
      ibm.power_ibmi.ibmi_cl_command:
        cmd: "QSYS/WRKCFGSTS CFGTYPE(*LIN)"
      register: all_line_descriptions_result
      when: present_ip_interface_line_description is undefined or present_ip_interface_line_description == None

    - name: Set default line_description
      ansible.builtin.set_fact:
        default_line_description: 'DEF{{ resource_name }}'

    - name: Give a default name of the line_description if the input value is not correct
      ansible.builtin.set_fact:
        present_ip_interface_line_description: "{{ default_line_description }}"
      when: present_ip_interface_line_description is undefined or present_ip_interface_line_description == None

    - name: Find existing line description
      ansible.builtin.include_tasks: find_existing_line_description.yml
      loop: '{{ all_line_descriptions_result.stdout_lines }}'
      loop_control:
        loop_var: lind_line
      when: present_ip_interface_line_description == default_line_description

    - name: Debug present_ip_interface_line_description
      ansible.builtin.debug:
        var: present_ip_interface_line_description

    - name: Vary on line description
      ansible.builtin.include_tasks: vary_on_line_description.yml

    - name: Create IP interface
      ibm.power_ibmi.ibmi_tcp_interface:
        line_description: '{{ present_ip_interface_line_description }}'
        vlan_id: '{{ present_ip_interface_vlanid }}'
        subnet_mask: '{{ present_ip_interface_netmask }}'
        internet_address: '{{ present_ip_interface_ip_address }}'
        state: 'present'
        associated_local_interface: '{{ present_ip_interface_associated_local_interface }}'
        type_of_service: '{{ present_ip_interface_type_of_service  }}'
        max_transmission_unit: '{{ present_ip_interface_max_transmission_unit  }}'
        auto_start: '{{ present_ip_interface_auto_start  }}'
        preferred_interface: '{{ present_ip_interface_preferred_interface }}'
        text_description: '{{ present_ip_interface_text_description }}'
        sec_to_wait: '{{ present_ip_interface_sec_to_wait | int }}'
        extra_params: '{{ present_ip_interface_extra_params }}'
        joblog: true

    - name: Query existing route
      ibm.power_ibmi.ibmi_sql_query:
        sql: "SELECT * FROM QSYS2.NETSTAT_ROUTE_INFO
  WHERE NEXT_HOP = '{{ present_ip_interface_next_hop }}'"
      register: route_info

    - name: Create route if present_ip_interface_next_hop is provided.
      ibm.power_ibmi.ibmi_cl_command:
        cmd: "ADDTCPRTE RTEDEST('{{ present_ip_interface_route_destination }}') NEXTHOP('{{ present_ip_interface_next_hop }}')
              {{ present_ip_interface_addition_options_for_addtcprte }}"
      when: present_ip_interface_next_hop and route_info.row | length == 0

- name: Ensure the IP interface is active
  ibm.power_ibmi.ibmi_tcp_interface:
    internet_address: '{{ present_ip_interface_ip_address }}'
    state: 'active'
